FROM fedora-toolbox:35

ENV POWERLINE_CONFIG_OVERRIDES='ext.shell={"colorscheme":"toolbox"}'

RUN dnf upgrade -y && \
    dnf install -y powerline powerline-fonts ansible golang java python3-pip && \
    dnf clean all
  
RUN wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/oc/latest/linux/oc.tar.gz && \
    tar xvf oc.tar.gz && \
    mv oc kubectl /usr/local/bin/ && \
    rm -f oc.tar.gz README.md

RUN wget https://mirror.openshift.com/pub/openshift-v4/clients/camel-k/1.4.2/camel-k-client-1.4.2-linux-64bit.tar.gz && \
    tar xvf camel-k-client-1.4.2-linux-64bit.tar.gz --no-same-owner && \
    mv kamel /usr/local/bin/ && \
    rm -f kamel.sha512 LICENSE NOTICE camel-k-client-1.4.2-linux-64bit.tar.gz 

RUN ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac) && \
    OS=$(uname | awk '{print tolower($0)}') && \
    OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.15.0 && \
    curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH} && \
    gpg --keyserver keyserver.ubuntu.com --recv-keys 052996E2A20B5C7E && \
    curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt && \
    curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt.asc && \
    gpg -u "Operator SDK (release) <cncf-operator-sdk@cncf.io>" --verify checksums.txt.asc && \
    grep operator-sdk_${OS}_${ARCH} checksums.txt | sha256sum -c - && \
    chmod +x operator-sdk_${OS}_${ARCH} && mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk

RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash && \
    mv kustomize /usr/local/bin/

CMD /bin/bash